# Generated by Django 2.0.4 on 2018-05-02 18:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paca_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='workers',
        ),
        migrations.AddField(
            model_name='job',
            name='worker',
            field=models.ManyToManyField(blank=True, related_name='worker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='job',
            name='manager',
            field=models.ManyToManyField(blank=True, related_name='manager', to='paca_app.Manager'),
        ),
    ]
