# Generated by Django 2.0.4 on 2018-05-02 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paca_app', '0002_auto_20180502_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='worker',
        ),
    ]
