# Generated by Django 2.0.2 on 2018-05-02 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paca_app', '0002_auto_20180502_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
