# Generated by Django 2.0.4 on 2018-05-02 20:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paca_app', '0003_remove_job_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='worker',
            field=models.ManyToManyField(blank=True, related_name='worker', to=settings.AUTH_USER_MODEL),
        ),
    ]
