# Generated by Django 2.0.2 on 2018-05-02 08:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paca_app', '0003_auto_20180502_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='workers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
